const menuArray = [
	{
		id: 1,
		title: 'Asada',
		category: 'Burritos',
		price: 5.50,
		// img:"https://en.wikipedia.org/wiki/Burrito#/media/File:Burrito.JPG",
		desc: 'Grilled Steak',
	},
	{
		id: 2,
		title: 'Barbacoa',
		category: 'Burritos',
		price: 5.50,
		// img: '../images/item-1.jpeg',
		desc: 'Steamed Beef',
	},
	{
		id: 3,
		title: 'Chile Relleno',
		category: 'Burritos',
		price: 5.50,
		// img: '../images/item-1.jpeg',
		desc: 'Cheese Stuffed Pepper',
	},
	{
		id: 4,
		title: 'Arriero',
		category: 'Burritos',
		price: 4.50,
		// img: '../images/item-1.jpeg',
		desc: 'Pork Green Sauce',
	},
	{
		id: 5,
		title: 'Chicharron',
		category: 'Burritos',
		price: 4.50,
		// img: '../images/item-1.jpeg',
		desc: 'Pork Skin Green Sauce',
	},
	{
		id: 6,
		title: 'Frijoles Con Queso',
		category: 'Burritos',
		price: 4.50,
		// img: '../images/item-1.jpeg',
		desc: 'Beans And Cheese',
	},
	{
		id: 7,
		title: 'Picadillo',
		category: 'Burritos',
		price: 4.50,
		// img: '../images/item-1.jpeg',
		desc: 'Ground Beef',
	},
	{
		id: 8,
		title: 'Puerco En Salsa Roja',
		category: 'Burritos',
		price: 4.50,
		// img: '../images/item-1.jpeg',
		desc: 'Pork Red Sauce',
	},
	{
		id: 9,
		title: 'Asada',
		category: 'Tacos',
		price: 2.50,
		// img: '../images/item-1.jpeg',
		desc: 'Grilled Steak',
	},
	{
		id: 10,
		title: 'Barbacoa',
		category: 'Tacos',
		price: 2.50,
		// img: '../images/item-2.jpeg',
		desc: 'Steamed Beef',
	},
	{
		id: 11,
		title: 'Asada',
		category: 'Tortas',
		price: 9.50,
		// img: '../images/item-3.jpeg',
		desc: 'Grilled Steak',
	},
	{
		id: 12,
		title: 'Barbacoa (Steamed Beef)',
		category: 'Tortas',
		price: 9.50,
		// img: '../images/item-4.jpeg',
		desc: 'Steamed Beef',
	},
	{
		id: 13,
		title: 'Jamon con Queso',
		category: 'Tortas',
		price: 9.50,
		// img: '../images/item-5.jpeg',
		desc: 'Ham & Cheese',
	},
	{
		id: 14,
		title: 'Burrito El Chavo',
		category: 'La Chiquita Favorites',
		price: 6.00,
		// img: '../images/item-6.jpeg',
		desc: 'Jamon Con Queso En La Plancha, Chicharon, Chile Con Queso',
	},
	{
		id: 15,
		title: 'Burrito El Nino',
		category: 'La Chiquita Favorites',
		price: 8.00,
		// img: '../images/item-7.jpeg',
		desc: 'Relleno, Asada, Crema, Aguacate',
	},
	{
		id: 16,
		title: 'Burrito Juarrez',
		category: 'La Chiquita Favorites',
		price: 6.00,
		// img: '../images/item-8.jpeg',
		desc: 'Asada, Chile Con Queso',
	},
	{
		id: 17,
		title: 'Quesadilla Flaco',
		category: 'La Chiquita Favorites',
		price: 7.50,
		// img: '../images/item-9.jpeg',
		desc: 'Jamon, Chile Con Queso, Asada, Mayonesa, Aguacate',
	},
	{
		id: 18,
		title: 'Torta Memo',
		category: 'La Chiquita Favorites',
		price: 13.00,
		// img: '../images/item-9.jpeg',
		desc: 'Chile Relleno, Asada, Chile Con Queso',
	},
	{
		id: 19,
		title: 'Platillos',
		category: 'Platillos',
		price: 10.50,
		// img: '../images/item-9.jpeg',
		descOne: 'Incluye 2 Guisados con Arroz y Frijoles Tortillas de Harina Maiz (No incluye Chile Rellenos)',
		descTwo:  'Includes 2 meat of choice Rice, Beans with Choice of Flour/Corn Tortillas (Does not include Chile Rellenos',
	},
	{
		id: 20,
		title: 'Sencilla',
		category: 'Quesadilla',
		price: 4.00,
		// img: '../images/item-9.jpeg',
		desc: 'Plain/ Only Cheese',
	},
	{
		id: 21,
		title: 'Cualquier Guisado',
		category: 'Quesadilla',
		price: 5.00,
		// img: '../images/item-9.jpeg',
		desc: 'Choice Of Meat',
	},
	{
		id: 22,
		title: 'Drinks & Sides',
		category: 'Drinks & Sides',
		price: 5.00,
		// img: '../images/item-9.jpeg',
		desc: 'Choice Of Meat',
	},
];
export default menuArray;